#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_Matrix_S1_1, motorA,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_2, motorB,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_3, motorC,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_4, motorD,        tmotorMatrix, openLoop)
#pragma config(Servo,  srvo_Matrix_S1_1, servoA,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_2, servoB,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_3, servoC,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_4, servoD,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
* enterthematrix.c
* -- This is a program to test MATRIX controllers and servos
* in order to find how if and how they work.
*/

//teleop code: we want to check if teleop is successful
void initControl()
{
  int threshold = 20;             /* Int 'threshold' will allow us to ignore low
                                    readings that keep our robot in perpetual motion.
                                    We need to tinker with the variable */

  while(true)                            // Infinite loop:
  {
    getJoystickSettings(joystick); // get joystick readings
    if(abs(joystick.joy1_y2) > threshold)   // If the right analog stick's Y-axis readings are either above or below the threshold:
    {
      motor[motorA] = joystick.joy1_y2;
      motor[motorC] = joystick.joy1_y2;
    }
    else                                    // Else if the readings are within the threshold:
    {
      motor[motorA] = 0;
      motor[motorC] = 0;
    }


    if(abs(joystick.joy1_y1) > threshold)   // If the left analog stick's Y-axis readings are either above or below the threshold:
    {
      motor[motorB] = joystick.joy1_y1;
      motor[motorD] = joystick.joy1_y1;
    }
    else                                    // Else if the readings are within the threshold:
    {
      motor[motorB] = 0;
      motor[motorD] = 0;
    }

  }
}

void setPowerAllMotors(int x){
// simultanously set power for all motors to the specified amount
motor[motorA] = x;
motor[motorB] = x;
motor[motorC] = x;
motor[motorD] = x;
}

void displayDebugMessage(string message){
	nxtDisplayString(4, "%s", message);
}

task main()
{
eraseDisplay();
displayDebugMessage("WELCOME TO THE MATRIX NEO");
wait1Msec(1000); //wait one second
//move foward at half speed for 3 seconds
setPowerAllMotors(50);
wait1Msec(3000);
//stop
setPowerAllMotors(0);
wait1Msec();
eraseDisplay();
displayDebugMessage("Manual Control Initiated");
initControl();

}
