#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Sensor, S2,     HTIRS2,         sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_Matrix_S1_1, motorA,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_2, motorB,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_3, motorC,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_4, motorD,        tmotorMatrix, openLoop)
#pragma config(Servo,  srvo_Matrix_S1_1, servoA,               tServoStandard)
#pragma config(Servo,  srvo_Matrix_S1_2, servoB,               tServoStandard)
#pragma config(Servo,  srvo_Matrix_S1_3, servoC,               tServoStandard)
#pragma config(Servo,  srvo_Matrix_S1_4, servoD,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c" //DO NOT TOUCH- These are the joystick drivers.
#include "/drivers/include/hitechnic-irseeker-v2.h" //IR sensor drivers- Don't touch this as well!

/*
* enterthematrix.c
* -- This is a program to test MATRIX controllers and servos
* in order to find how if and how they work.
*/

//teleop code: we want to check if teleop is successful
void initFirstControl()
{
  int threshold = 10;             /* Int 'threshold' will allow us to ignore low
                                    readings that keep our robot in perpetual motion.
                                    We need to tinker with the variable */

  while(true)                            // Infinite loop:
  {
    getJoystickSettings(joystick); // get joystick readings
    if(abs(joystick.joy1_y1) > threshold)   // If the right analog stick's Y-axis readings are either above or below the threshold:
    {
      motor[motorA] = joystick.joy1_y1;
    }
    else                                    // Else if the readings are within the threshold:
    {
      motor[motorA] = 0;
    }


    if(abs(joystick.joy1_y2) > threshold)   // If the left analog stick's Y-axis readings are either above or below the threshold:
    {
      motor[motorB] = joystick.joy1_y2;
    }
    else                                    // Else if the readings are within the threshold:
    {
      motor[motorB] = 0;
    }

    //and the following is for the 2nd controller.

	if(abs(joystick.joy2_y1) > threshold){
		motor[motorC] = joystick.joy2_y1;
	} else {
		motor[motorC] = joystick.joy2_y1;
	}

	if(abs(joystick.joy2_y2) > threshold){
		motor[motorC] = joystick.joy2_y2;
	} else {
		motor[motorD] = joystick.joy2_y2;
	}

  }
}

// This code may be VERY problematic. Be careful if using
void moveToBeacon(){
	int _dirAC = 0;
	 int acS1, acS2, acS3, acS4, acS5 = 0;

	 int maxSig = 0; // the max signal strength from the seeker.
	 int val = 0; // the translated directional value.


	 // we are going to set DSP mode to 1200 Hz.
	 //HTIRS2_DSP_MODE _mode = DSP_1200;

	 // attempt to set to DSP mode.
	 if (HTIRS2setDSPMode(HTIRS2, DSP_1200) == 0)
	 {
	 }

	 // loop continuously and read from the sensor.
	 while(true)
	 {
	 // read the current modulated signal direction
	 _dirAC = HTIRS2readACDir(HTIRS2);
	 if (_dirAC < 0)
	 {
	 break;
	 }

	 // Get the AC signal strength values.
	 if (!HTIRS2readAllACStrength(HTIRS2, acS1, acS2, acS3, acS4, acS5 ))
	 {
	 break;
	 } else {
	 // find the max signal strength of all detectors.
	 maxSig = (acS1 > acS2) ? acS1 : acS2;
	 maxSig = (maxSig > acS3) ? maxSig : acS3;
	 maxSig = (maxSig > acS4) ? maxSig : acS4;
	 maxSig = (maxSig > acS5) ? maxSig : acS5;
	 }

	 // figure out which direction to go...
	 // a value of zero means the signal is not found.
	 // 1 corresponds to the far left (approx. 8 o'clock position).
	 // 5 corresponds to straight ahead.
	 // 9 corresponds to far right.

	 // first translate directional index so 0 is straight ahead.
	 val = _dirAC - 5;

	 // calculate left and right motor speeds.
	 motor[motorA] = 50 + 30 * val;
	 motor[motorB] = 50 - 30 * val;

	 // wait a little before resuming.
	 wait10Msec(2);

	}
}

bool checkIfTouching(){ //micah wanted touch sensor stuff i think.
	if (SensorValue(touch) == 1){ 
		return true;
	} else { 
		return false; 
	}
}


void flingBlocks(){
// reserved for when micah finishes his apperatus (Techical term for thingy)
}

void panicButton() //YES I'M MAKING A PANIC BUTTON DEAL WITH IT
{
	// Each controller will have a designated panic button. also this will automatticly kick in if connection is lost
	if (joystick.joy1_TopHat == 1){
		enterSafeMode(0);
	} else {
		//Umm.. I don't know what to put here.... I'll think of something
	}
}

void enterSafeMode(){

//STOP EVERYTHING NOTHING CAN MOVE
	setPowerAllMotors(0);


}


void setPowerAllMotors(int x){
// simultanously set power for all motors to the specified amount
motor[motorA] = x;
motor[motorB] = x;
motor[motorC] = x;
motor[motorD] = x;
}

task main()
{

initFirstControl();


}
