#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Sensor, S2,     HTIRS2,         sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_Matrix_S1_1, motorA,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_2, motorB,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_3, motorC,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_4, motorD,        tmotorMatrix, openLoop)
#pragma config(Servo,  srvo_Matrix_S1_1, servoA,               tServoStandard)
#pragma config(Servo,  srvo_Matrix_S1_2, servoB,               tServoStandard)
#pragma config(Servo,  srvo_Matrix_S1_3, servoC,               tServoStandard)
#pragma config(Servo,  srvo_Matrix_S1_4, servoD,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c" //DO NOT TOUCH- These are the joystick drivers.
#include "/drivers/include/hitechnic-irseeker-v2.h" //IR sensor drivers- Don't touch this as well!

/*
* enterthematrix.c
* -- This is a program to test MATRIX controllers and servos
* in order to find how if and how they work.
*/

//teleop code: we want to check if teleop is successful
void initControl()
{
  int threshold = 10;             /* Int 'threshold' will allow us to ignore low
                                    readings that keep our robot in perpetual motion.
                                    We need to tinker with the variable */

  while(true)                            // Infinite loop:
  {
    getJoystickSettings(joystick); // get joystick readings
    if(abs(joystick.joy1_y1) > threshold)   // If the right analog stick's Y-axis readings are either above or below the threshold:
    {
      motor[motorA] = joystick.joy1_y1;
    }
    else                                    // Else if the readings are within the threshold:
    {
      motor[motorA] = 0;
    }


    if(abs(joystick.joy1_y2) > threshold)   // If the left analog stick's Y-axis readings are either above or below the threshold:
    {
      motor[motorB] = joystick.joy1_y2;
    }
    else                                    // Else if the readings are within the threshold:
    {
      motor[motorB] = 0;
    }

    //and the following is for the 2nd controller.

	if(abs(joystick.joy2_y1) > threshold){
		motor[motorC] = joystick.joy2_y1;
	} else {
		motor[motorC] = joystick.joy2_y1;
	}

	if(abs(joystick.joy2_y2) > threshold){
		motor[motorC] = joystick.joy2_y2;
	} else {
		motor[motorD] = joystick.joy2_y2;
	}

  }
}

// This code may be VERY problematic. Be careful if using


void setPowerAllMotors(int x){
// simultanously set power for all motors to the specified amount
	motor[motorA] = x;
	motor[motorB] = x;
	motor[motorC] = x;
	motor[motorD] = x;
}


void enterSafeMode(){

//STOP EVERYTHING NOTHING CAN MOVE
	setPowerAllMotors(0);
}


void panicButton() //YES I'M MAKING A PANIC BUTTON DEAL WITH IT
{
	// Each controller will have a designated panic button. also this will automatticly kick in if connection is lost
	if (joystick.joy1_TopHat == 1){
		enterSafeMode(0);
	} else {
		//Umm.. I don't know what to put here.... I'll think of something
	}
}


task main()
{
initControl();
}
